version: "3"
services:
  postgres_scim:
    image: postgres
    ports:
      - "5400:5432"
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "scimapp"
    healthcheck:
      test: pg_isready -U postgres
  scim-app:
    build: .
    ports:
      - "443:443"
    environment:
      DB_HOST: "localhost"
      DB_PORT: 5400
      BASE_USERNAME: "username"
      BASE_PASSWORD: "username@2000"
    depends_on:
      - postgres_scim
        